version: "3.8"

services:
  registered-email-address-web:
    build:
      context: .
      dockerfile: repositories/registered-email-address-web/dev.dockerfile
#      args:
#        SSH_PRIVATE_KEY: $(cat ~/.ssh/id_rsa)
#        SSH_PRIVATE_KEY_PASSPHRASE: ${SSH_PRIVATE_KEY_PASSPHRASE}
    environment:
      - FEATURE_FLAG_ENABLE_TRUSTS_WEB_07112022=1
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - /app/dist
      - ./repositories/registered-email-address-web:/app
    tty: true
    command:
      "npm run start:dev"
#      sh